name: ease_the_sorrow_by_milktea

avatar: https://github.com/supermt/supermt.github.io/blob/main/logo.jpg 

remote_theme: "mmistakes/minimal-mistakes@4.21.0"

minimal_mistakes_skin: "contrast"

plugins:
  - jekyll-include-cache
